[build]
  base = "web"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.9.0"
  NEXT_PUBLIC_API_URL = "https://personalchatapp-1.onrender.com/api"
  NEXT_PUBLIC_SOCKET_URL = "https://personalchatapp-1.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
